version: '3'

services:
  app_prod:
    build:
      context: .
      dockerfile: prod.dockerfile
    restart: on-failure
    container_name: app_prod
    environment:
      VIRTUAL_HOST: 'graphql-test.com' # You can change it when you have a domain
    env_file:
      - ./.env
    ports:
      - '4000:4000'

  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_ENVIRONMENT: dev
    restart: on-failure
    container_name: app_dev
    command: 'mix deps.get && mix phx.server'
    environment:
      DATABASE_URL: mysql://root:root@app_mysql/app_development
    volumes:
      - '.:/app'
    ports:
      - '4000:4000'
    depends_on:
      - app_mysql
    networks:
      - netw

  app_mysql:
    image: mysql:8.0.20
    container_name: app_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '9005:3306'
    networks:
      - netw

networks:
  netw:
    external:
      name: netw
